/// Flutter icons MyCustomIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcon
///      fonts:
///       - asset: fonts/MyCustomIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyCustomIcon {
  MyCustomIcon._();

  static const _kFontFam = 'MyCustomIcon';

  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xf0d5, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
}
